jdk: oraclejdk8
language: android
android:
  components:
  - build-tools-28.0.3
  - android-28
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew exportVersion --daemon"
# The plugin will build it and publish it, we currently don't have
# a way to upload an existing apk.
# See https://github.com/Triple-T/gradle-play-publisher/issues/360
# TODO: But in non-master branches, it will still be published.....
- "./gradlew :app:publishReleaseApk --daemon --parallel"
before_install:
- yes | sdkmanager "platforms;android-28"
- chmod a+x gradlew
- openssl aes-256-cbc -K $encrypted_7aab63907238_key -iv $encrypted_7aab63907238_iv -in secrets.tar.enc -out ./secrets.tar -d
- tar xvf secrets.tar
before_deploy:
- export VERSION=$(cat version.txt)
- export VERSION_CODE=$(cat version_code.txt)
- git tag $VERSION_CODE
# Rename
- mv "app/build/outputs/apk/release/app-release.apk" "app/build/outputs/apk/release/app.apk"
deploy:
  name: ${VERSION}
  body: Snapshot version automatically generated by Travis CI. Please be cautious to experience due to potential bugs.
  prerelease: true
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rvV6A3CKwvyo0rUHYq3kHLzEukLZaT4Dddqn1tK7MSoD33MZqTo5VKtS6p+bKFQzI6aqdpDl9eminv9HsYO9ogtIRP5GuPhi+UMNX/RNC3ISwgPjMT0WkZKovNqfQxr2QLrg95NrdI+tZ4MPAlprtAB6onkFcssS6pPsm3UZ/RAB0s5PT/+pBVIplWD93hx805s1Soijg4T22HyYvLr26ZqcHud2lx6ams1GT73ZAxx5HZHQYBKJvp4Qnsh16XWlvQCTMc7kCS8O1xFCpN33BDpcBeoCynhO5zIV7V7y9S6RtfnJMoSGjCoaPOAJdPRgqWgyfZCCdLoJBRO7Ig2IAKNNENaSwvsDsTm2nQ3DbYcVY6aRX+s1m2Vysvh3pxkxNaKTl58pXsTlEdYvTFJ1Bd1Y3m6E3Y9k7UiRsSw2PAcA4iRCAU3WaSgekJ03uOMQoZUT5xAiRfTORL4cv5TMKwWq7dl7gn2Ild1sb3ajT1JgNLVyTKrzG4qgxnIWyS28pLosTRurabheA6JbkM1PGuUyLUkh1UBQ2WkoKUjUaJ9v6+XmT6NdFD70ukdeE9QijVq1SlvIDX/iPCkSsY6fMlM18bfkO44AhYvkNow6uMIoKrZf5E1izIkwGAeGlDB/aqxpZHcW7zgkpys/q6MWSfwxcY2eIZUi7V9Epr0kGi0=
  file: app/build/outputs/apk/release/app.apk
  on:
    repo: Trumeet/MiPushTester